### ISSUE TITLE
API: Create endpoint to get 3D data of a bed

### ISSUE THREAD

**Issue by pbrozi** [naturerobots/HSOS-SEP-PlantMap-2022#112]
- [ ] Provide functionality to get 3D data of a bed over gRPC
- [ ] Provide REST endpoint path: companies/{company_id}/gardens/{garden_id}/beds/{bed_id}/3d

**Comment by lniehaus** [comment]
We need the path to the PLY files on the Storage System
Example: "http://localhost:8000/media/pointclouds/ply/e1ef73b1258b475a996d2b72924c27ac/0bf37a0851b7402d88674e153f58e6f8.ply"

In addition to the Path on the Storage System we need Informations about single plants themself to create a 3d overlay
![image](https://user-images.githubusercontent.com/12699419/180226003-c1ebbe1c-b961-4a32-a024-62bdfb55af83.png)
