### ISSUE TITLE
Wrong position of points on image in leaflet map

### ISSUE THREAD

**Issue by jarkenau** [naturerobots/HSOS-SEP-PlantMap-2022#127]
I plotted the origin of the world coordinate system on Google Maps and on the Leaflet Map.

```
"latitude": 52.317118,
"longitude": 7.630613
```
The point's location is on a completely  different bed, any idea why? @lucaslootalot @dobro929 

![image](https://user-images.githubusercontent.com/49768113/174396893-40d39b6b-03a5-4c84-bfa1-30fb4cc44413.png)

**Comment by jarkenau** [comment]
I think the image needs to be rotated by 180°, since the tent structure has to be on the top. 

![image](https://user-images.githubusercontent.com/49768113/174398440-7254e1c7-9830-4b5e-80cd-e0a78b241ada.png)

**Comment by lucaslootalot** [comment]
You are absolutely right. Are you going to rotate the picture or should I just do it?

**Comment by jarkenau** [comment]
I have no idea how to do it, so it's up to you :grin:

**Comment by lucaslootalot** [comment]
Not 100% accurate, but looks more correct. 😄 
![image](https://user-images.githubusercontent.com/57572111/174399837-089507bb-682e-4647-8ac9-a337f67d1067.png)

**Comment by lucaslootalot** [comment]
@jarkenau Can the issue be closed?
