### ISSUE TITLE
Api endpoint: Corrections and suggestions

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#130]
API Endpoint (**companies/<int:company_id>/gardens/<int:garden_id>/beds/<int:bed_id>/plants**) doesn't work in the current dev branch. The method **getPlants** needs the variable bed_id. 
**Suggestion:** `getPlants(request, company_id: string, garden_id: string, bed_id: string)`

We also need to change `name` to `plant`.

![grafik](https://user-images.githubusercontent.com/87453514/175002940-018af1cd-f367-4b43-b495-1a7845d462f2.png)

**Comment by pbrozi** [comment]
Problem fixed, dev branch updated.

**Comment by lniehaus** [comment]
in the current dev branch the mock data JSON does not have the changed attribute from "name" to "plant"

![image](https://user-images.githubusercontent.com/12699419/175032496-d8f7185d-851c-4dea-971e-6e3ddc3bc316.png)
