### ISSUE TITLE
Integrate plants endpoint

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#131]
wait until #130 is finished to integrate **companies/<int:company_id>/gardens/<int:garden_id>/beds/<int:bed_id>/plants**
wait until #171

- [x] #130 
- [x] #171
- [x] change `cropsApi.ts`
- [x] change `cropsStore.ts`

**Comment by dobro929** [comment]
@Anafabula @jarkenau Since #171 is done, is there already a user where I can query the data? The **test user** does not work for querying the data.

**Comment by jarkenau** [comment]
Currently, there is no default data in the database, so you have to create a company and garden manually, but we are working on that in #186 and #172 (should be done by Thursday).

**Comment by jarkenau** [comment]
I updated the `dev` Branch, after a fresh installation of the Dev-Container the following steps to should get the default data running. Further automatization is planned in #190 

1. `cd django`
2. `python3 manage.py makemigrations`
3. `python3 manage.py migrate`
4. `python3 manage.py loaddata user company garden bed`
5. `celery -A restapi.tasks worker --loglevel=info`
6. `python3 manage.py runserver` (in a new terminal)

**Comment by dobro929** [comment]
Thanks for the detailed answer, loading the demo data works 👍🏼

**Comment by dobro929** [comment]
Thanks for the detailed answer, loading the demo data works 👍🏼

**Comment by dobro929** [comment]
@jarkenau @Anafabula I just noticed that `soil_humidty` is not spelled correctly. There is an missing **i**. Can we correct that? And if possible can we rename `bedid` into `bed_id` 🙏🏼😄

**Comment by jarkenau** [comment]
@dobro929 I included the suggested changes. 

Also in the startup process you now need to use: 
`python3 manage.py loaddata user company garden bed permissions`

**Comment by dobro929** [comment]
@jarkenau this does not seem to be working 🤔 

![grafik](https://user-images.githubusercontent.com/87453514/182234226-459e7045-8028-4c20-9907-d0952fe7a641.png)

**Comment by jarkenau** [comment]
@pbrozi deleted some migrations due to some errors which were hard to fix. You probably need to empty the database. I just used `docker system prune -a --volumes` to uninstall all docker volumes and images from the pc and then reopen the development container to get a fresh installation.

**Comment by lucaslootalot** [comment]
> I updated the `dev` Branch, after a fresh installation of the Dev-Container the following steps to should get the default data running. Further automatization is planned in #190
> 
> 1. `cd django`
> 2. `python3 manage.py makemigrations`
> 3. `python3 manage.py migrate`
> 4. `python3 manage.py loaddata user company garden bed`
> 5. `celery -A restapi.tasks worker --loglevel=info`
> 6. `python3 manage.py runserver` (in a new terminal)

@jarkenau Regardless of #190 please document this.
