### ISSUE TITLE
Can we change the maximum upload size of files?

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#144]
I wanted to replace the image on the login and registration page with a newer one, but the size is too large. 
Can we **increase** this number?

![grafik](https://user-images.githubusercontent.com/87453514/175359590-223da0d7-85b2-46e3-9c4a-84a9f76d357b.png)

**Comment by lucaslootalot** [comment]
@dobro929 Isn't 2.5 MB a little large? Even if we are to assume that an internet connection is always given.
