### ISSUE TITLE
Crops table harvest values

### ISSUE THREAD

**Issue by pbrozi** [naturerobots/HSOS-SEP-PlantMap-2022#157]
In the current mock-up a time period, when the crops can be harvested, is requested (column 7). From SEEREP I only get a percentage double value (e.g. 0.9). How should this be interpreted/calculated?

![image](https://user-images.githubusercontent.com/82388584/176191023-247c2d28-6916-4255-b3dd-92e1ebe9b0bb.png)

**Comment by gwoeckner** [comment]
0.9 indicates a percentage of 90% harvest readiness. You also have a start date when the plant is planted. Now it's quite simple to calculate the remaining days :)

**Comment by lucaslootalot** [comment]
@gwoeckner How do I calculate the remaining days for harvesting if the plant has a value of 0.0 on the start day or takes so long to be harvested that the value of 0.1 is reached so late that the value could not be calculated for a week, for example? Or have I understood something wrong?

**Comment by lucaslootalot** [comment]
@pbrozi We talked about it yesterday, can the issue be closed then or are there still open questions on this topic?
