### ISSUE TITLE
Testing first frontend setup

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#16]
- update _dev_ branch
- `npm run dev`

**Comment by lucaslootalot** [comment]
@dobro929 What is to be tested?

**Comment by lucaslootalot** [comment]
@dobro929 After `npm run dev`:
> warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration

**Comment by dobro929** [comment]
@lucaslootalot you can ignore the warning. We don't have any custom classes at the moment.

**Comment by fmarahre** [comment]
tests successful
