### ISSUE TITLE
Basic Data for User, Company, Garden, Beds

### ISSUE THREAD

**Issue by lniehaus** [naturerobots/HSOS-SEP-PlantMap-2022#162]
We need to seed standard data into the Database, so the api will work after migrating and starting the server.
https://docs.djangoproject.com/en/4.0/howto/initial-data/

**Comment by jarkenau** [comment]
Way to go in Django https://docs.djangoproject.com/en/4.0/howto/initial-data/

**Comment by spuetz** [comment]
This is exactly the right way. You can also write custom commands for manage.py for imports from other formats.
