### ISSUE TITLE
User object must be extended

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#169]
We receive other information about the **user** from the registration process, we should also store this information.
For example, I would suggest that we send this json to the **register** endpoint.
```json
{
   "username":"exampleUser",
   "password":"examplePassword",
   "lastname":"exampleName",
   "firstname":"exampleName"
}
```

**Comment by lucaslootalot** [comment]
We should check if the personal address is necessary.

```json
{
   "username":"exampleUser",
   "password":"examplePassword",
   "lastname":"exampleName",
   "firstname":"exampleName",
-   "street":"exampleStreet",
-   "number":"1234",
-   "city":"exampleCity",
-   "postalcode":"1234"
}
```

**Comment by dobro929** [comment]
⚠️ To be able to describe this accurately, we first need **more information** about the **registration process**.

**Comment by dobro929** [comment]
From the discussion about the registration process, it has emerged that we can **create a user without a company and garden**. For **creating a company and a garden** I have created a separate issue #172.
