### ISSUE TITLE
Gardenimage Upload API

### ISSUE THREAD

**Issue by lucaslootalot** [naturerobots/HSOS-SEP-PlantMap-2022#170]
The image is stored as a `base64-encoded data url`. We also need the coordinates of the placement.  

❗ It may happen that `positions` are extended by `bottomRight`. #151

@jarkenau Can you work with the data url to generate the image as a tile?

JSON could look like this:
```json
{
  "data": "data:image/png;base64,GVsbG8sIFdvcmxkIQ==",
  "positions": {
    "topLeft": {
      "lat": "52.31703822683545",
      "lng": "7.630155086517335"
    },
    "topRight": {
      "lat": "52.31703822683545",
      "lng": "7.630155086517335"
    },
    "bottomLeft": {
      "lat": "52.31703822683545",
      "lng": "7.630155086517335"
    }
  }
}
```

**Comment by jarkenau** [comment]
@lucaslootalot It would be better if I get the image as a `.png`, or best case as `.tif` for georeferencing it.  Then I don't have to do a bunch of conversion. Especially for large images, which I image the drone picture will be, this could make a difference. 

Also, I would propose a slightly different JSON structure, so that it will be easier to add more points later. We just use an Array to store all the position and the referencing is done via the pixel's x, y coordinate and the latitude and longitude. Is this possible for you? 

```
{
   "img": ...
   "positions":[
      {
         "x":0,
         "y":0,
         "lat":52.31703822683545,
         "lng":7.630155086517335
      },
      {
         "x":"Img-Width",
         "y":0,
         "lat":52.31703822683545,
         "lng":7.630155086517335
      },
      "..."
   ]
}
```

**Comment by lucaslootalot** [comment]
I don't quite understand why we need x and y. The script we are working with assigns the cooridnates based on the names "topRight", etc. Your idea with the array of positions would of course make more sense, but I think it would be sufficient for now to implement it less flexibly with the names.  
The image is a `.png`. Do I understand correctly that you want to have the image separately and not as a data url? Is then the `img` field in your JSON the URL to the image?

**Comment by jarkenau** [comment]
OK, let's do it with the currently implemented script. It would be best to have the image separate, so I can directly save it. The `img` field would then be the URL to retrieve the image after it's saved.

**Comment by lucaslootalot** [comment]
Then i would send you the following JSON. What will the endpoints be called then?

```json
{
  "imgUrl": null,
  "positions": {
    "topLeft": {
      "lat": "52.31703822683545",
      "lng": "7.630155086517335"
    },
    "topRight": {
      "lat": "52.31703822683545",
      "lng": "7.630155086517335"
    },
    "bottomLeft": {
      "lat": "52.31703822683545",
      "lng": "7.630155086517335"
    }
  }
}
```

**Comment by jarkenau** [comment]
Currently, the upload and download are under the following endpoint:
https://github.com/naturerobots/HSOS-SEP-PlantMap-2022/blob/6820c80300afc3107abecf8c52a55e1d9fe07cfb/django/restapi/urls.py#L21

Should we use this or change something?

Also, another point occurred to me, do we allow uploading different file formats like `.png`, `.jpg` etc. or do we just focus on one?

**Comment by lucaslootalot** [comment]
Don't we need a second endpoint for the JSON then? As we have to upload and download image and image data separately.

Since every garden needs a company, this should actually fit. Does this fit with your implementation of the company-garden-user structure?

We should only focus on one image format, as we make it a `.png` regardless of the format that is uploaded. Making it `.tif` instead should not be a problem. I then just need to test how it would behave to use `.tif` in combination with the map.

**Comment by jarkenau** [comment]
@lucaslootalot For the `GET` it's obvious what I should return, but what's with the `POST`? Should even anything be returned?

**Comment by lucaslootalot** [comment]
Maybe simple status description JSON for `POST` response?
```
{
  "status": 200,
  "description": "Garden successfully uploaded"
}
```
