### ISSUE TITLE
Endpoints to create a company and a garden

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#172]
After registration we start an **onboarding process** where the user can create a **company** and a **garden**. Therefore we need 2 more endpoints.

Here is a rough example:

1. `Post: /companies`
2. `Post: /companies/{companyId}/gardens`

Both endpoints should be **authenticated**.

They have the same body for now. We will add an **optional address** to both later on.
```json
{
    "name": "exampleName"
}
```
If the object was created successfully, we get the **id** as return.

**Comment by jarkenau** [comment]
@dobro929 Not sure if I got that correctly, both endpoints should just accept a name from the request? :thinking:

**Comment by dobro929** [comment]
@jarkenau Yes, we will extend it later, but make sure you set the user as admin when we create a company.

**Comment by jarkenau** [comment]
I will probably implement it without requiring admin privileges, since @pbrozi is still working on the permission system.
