### ISSUE TITLE
Create ER Diagramm

### ISSUE THREAD

**Issue by lniehaus** [naturerobots/HSOS-SEP-PlantMap-2022#174]
There is currently no ER Diagramm for the Database.
We need to define the relations between user, company, garden, bed etc..
Especially for the permission system proposed in the User Stories 2 we need a clean DB design.

![image](https://user-images.githubusercontent.com/12699419/177347310-dcb26a59-f899-48ab-88c9-1cef6a830bf2.png)

**Comment by pbrozi** [comment]
![Image](https://user-images.githubusercontent.com/82388584/179770156-4530a7c2-50b1-426a-8700-d6a629d3f66e.png)
