### ISSUE TITLE
Create API endpoints for garden and bed information

### ISSUE THREAD

**Issue by pbrozi** [naturerobots/HSOS-SEP-PlantMap-2022#18]
Garden endpoints should include:

- [x] `GET` for the IDs of all gardens associated with a company
- [ ] `GET` for meta information of a specific garden

Bed endpoints should include:

- [ ] `GET` for all beds
- [ ] `GET` for meta information about a specific bed

**Comment by jarkenau** [comment]
Planning poker :black_joker: results: 

- Sum: 150
- Average: 18.75
