### ISSUE TITLE
API: Create endpoint to get data from a sensor

### ISSUE THREAD

**Issue by pbrozi** [naturerobots/HSOS-SEP-PlantMap-2022#19]
- [ ] Provide functionality to get data from a sensor over gRPC
- [ ] Provide REST endpoint path: `companies/{company_id}/gardens/{garden_id}/beds/{bed_id}/sensors/{sensor_id}`

**Comment by jarkenau** [comment]
Planning poker :black_joker: results: 

- Sum: 127
- Average: 15.875

**Comment by lniehaus** [comment]
![image](https://user-images.githubusercontent.com/12699419/176189054-47f1e4ae-d80c-4379-8e49-c1efd5ea9989.png)
