### ISSUE TITLE
Demo data

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#201]
I've been thinking about some demo data to match each case 🤔 

user id | name | admin (company id) | admin (garden id) | only permission (company id) | only permission (garden id)
--|--|--|--|--|--
1 | Admin | 1,2 | | |
2 | Gardener-1 | | | 1 |
3 | Gardener-2 | | 3 |  |
4 | Gardener-3 | | | | 4
5 | Gardener-4 | | | | 

company id | name | owns (garden id)
--|--|--
1 | Company-1 | 1,2 
2 | Company-2 | 3 
3 | Company-3 | 
4 | Company-4 | 4

garden id | name | image
--|--|--
1 | Garden-1 | x
2 | Garden-2 | 
3 | Garden-3 | x
4 | Garden-4 | x

Please give the marked gardeners this **picture** and the **coordinates**.

```
src: "https://cloud.naturerobots.de/apps/files_sharing/publicpreview/xZj9ytRt8WKr5cw?file=/goeoentueuegs_ibbenbueren_new2.jpg&fileId=28565&x=1920&y=1080&a=true",
top_right: new LatLng(52.31724604719058, 7.630553394556046),
top_left: new LatLng(52.3170773725588, 7.630054503679276),
bottom_left: new LatLng(52.31686606722232, 7.630242593586445),  
```

**Comment by jarkenau** [comment]
@dobro929 Do you have to have any special `Beds` config for the gardens?

**Comment by jarkenau** [comment]
@pbrozi I looked into the database structure and created the following figure. Currently, it is not possible to add more than one garden to a company, due to the 1 to 1 relationship.
![db drawio](https://user-images.githubusercontent.com/49768113/183251310-0cd4d5af-4d56-4193-b4b8-0da4c60bf9e3.png)

**Comment by jarkenau** [comment]
@pbrozi It is currently not possible to add the same garden to multiple companies, due to the 1 to 0...n relationship between them. Could you look into that?
![db](https://user-images.githubusercontent.com/49768113/183251528-78d948d1-09b1-4d1e-a05f-5260c3b57a5f.png)

**Comment by dobro929** [comment]
@jarkenau No, we don't need any special configs, just beds 😆

**Comment by pbrozi** [comment]
@jarkenau We never talked about a garden belonging to multiple companies. One garden is owned by exactly one company but you can already give access to a garden to any user you want. Isn't that sufficient? Otherwise many changes would be necessary.

**Comment by jarkenau** [comment]
@pbrozi Never mind I misunderstood the tables from Timo, everything is fine :grin:

**Comment by dobro929** [comment]
@jarkenau Im logged in as `Gardener-3` and i have access to **garden (id: 4)**, where do i get the company id from?
Request i have access to: `companies/4/gardens/4`

**Comment by pbrozi** [comment]
The endpoint `GET: companies/{company_id}/gardens` returns all gardens of the requested company (company id is in the URL) the user has permissions on.

**Comment by dobro929** [comment]
@pbrozi Yes, but where do i get the company id from?

**Comment by pbrozi** [comment]
To access this endpoint, the requesting user has to be user of the company, otherwise anyone could see which gardens a company has. To get all companies the user has permissions on, use the endpoint `GET: companies`.

**Comment by dobro929** [comment]
`GET: companies` 200 but empty array ❌ 
`GET: companies/4/gardens` 403 Forbidden ❌ 
`GET: companies/4/gardens/4` 200 garden object ✔️

**Comment by pbrozi** [comment]
Okay, I see. If a user has user permissions on a company, he cannot access any gardens. Garden permissions for each garden need to be set, too. If you only have permission for a single garden, you cannot obtain the corresponding company id.

I would implement the following changes:
- Every user of a company can get all gardens.
- Add an endpoint `GET: gardens` to get all gardens the user has access on.

**Comment by dobro929** [comment]
@fmarahre and I just noticed that with the latest updates the endpoint `GET: companies/{company_id}/gardens/{garden_id}/beds` does not work anymore. Even as **Admin** we get **403 Forbidden**.
