### ISSUE TITLE
Permission endpoints

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#213]
Im not sure if the permission system works that way. How do I as admin get the `user_id` of the user I want to give rights to?
Example:
`POST: /companies/{company_id}/createPermission`
```json
{
  "user_id": "42",
  "permission": "a"
}
```

**Comment by pbrozi** [comment]
The user you want to give permissions currently needs to tell you his or her id. The user can obtain it with `GET: /user`.

Would it make sense to implement an endpoint to get the user id from a user specified by username? This endpoint would be accessible for any registered user.

**Comment by dobro929** [comment]
I think the better solution is to replace `user_id` with `username` and the server then searches for the user_id itself.
