### ISSUE TITLE
clean up ghcr

### ISSUE THREAD

**Issue by jarkenau** [naturerobots/HSOS-SEP-PlantMap-2022#220]
Currently, there are some old images, in the ghcr of this repository:

![image](https://user-images.githubusercontent.com/49768113/184477932-2dd3052a-da5a-4683-94d4-8fa2c376980a.png)

**Everything except the second one** should be deleted. Additionally, the remaining one should be made public

**Comment by mklpiening** [comment]
I deleted the two old images, but the visibility can just be changed by @spuetz
