### ISSUE TITLE
Keep user logged in when reloading page

### ISSUE THREAD

**Issue by gwoeckner** [naturerobots/HSOS-SEP-PlantMap-2022#238]
- [x] implement [Pinia Plugin](https://github.com/prazdevs/pinia-plugin-persistedstate)
- [x] persist all stores

**Comment by lniehaus** [comment]
The login informations are saved in the vue store. We might have to switch to the localstorage to stay persistant.

**Comment by dobro929** [comment]
[This](https://github.com/vuejs/pinia/issues/309) should fix the bug
