### ISSUE TITLE
weather: icons

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#24]
Lookup weather icons to display weather data.

**Comment by lucaslootalot** [comment]
In reference to the Open Weather Icons, 9 different icons are needed to display the weather.

To look up: [Weather Conditions - Weather icons](https://openweathermap.org/weather-conditions)

@dobro929 Do the icons match the general style? If not, other icons have to be found.

**Comment by dobro929** [comment]
We could use Fontawesome, it has a [free license](https://fontawesome.com/license/free). I have picked out the corresponding icons for this purpose. You can also have another look at them [here](https://fontawesome.com/search?q=weather&m=free&s=solid%2Cbrands).

<html><body>


Day icon | Night icon | FA Day icon | FA Night icon  | Description
-- | -- | -- | -- | --
![](http://openweathermap.org/img/wn/01d.png) | ![](http://openweathermap.org/img/wn/01n.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166663636-0ed0b423-b771-4e75-8c78-c7ad3880d3ec.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166663721-e8440077-ee2e-4cba-bb68-3cd974365f06.png) | clear sky
![](http://openweathermap.org/img/wn/02d.png) | ![](http://openweathermap.org/img/wn/02n.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166663828-db18bb31-62bd-4042-bc50-b2d8b8e9b9ef.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166663798-964d91b2-10f2-443d-a03d-eaebd01cee80.png) |few clouds
![](http://openweathermap.org/img/wn/03d.png) | ![](http://openweathermap.org/img/wn/03n.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166663947-db89696b-aa65-49f0-81c2-6a053ccdc848.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166663952-9591b1fb-9b7b-425c-8b23-0216e8c27c2f.png) | scattered clouds
![](http://openweathermap.org/img/wn/04d.png) | ![](http://openweathermap.org/img/wn/04n.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664378-5ff4ae40-9a03-4eb6-ae80-05166da34ac1.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664370-824750d8-d837-40b3-aef7-2a78c73ba280.png) |broken clouds
![](http://openweathermap.org/img/wn/09d.png) | ![](http://openweathermap.org/img/wn/09n.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664335-f8e4040d-1742-4d31-bf14-473bcdf2da83.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664331-fe8373e4-60f2-4032-8a1f-a8dcc9689087.png) |shower rain
![](http://openweathermap.org/img/wn/10d.png) | ![](http://openweathermap.org/img/wn/10n.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664261-c0561178-2acc-45c2-b23a-3f1e6834a828.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664292-07cc03fa-396b-46f8-84f0-74c619c87127.png) |rain
![](http://openweathermap.org/img/wn/11d.png) | ![](http://openweathermap.org/img/wn/11n.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664193-2aa9e114-78a2-4815-82aa-d0173cee7cca.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664189-08071e62-5ba1-4424-821c-33d9cca4a583.png) |thunderstorm
![](http://openweathermap.org/img/wn/13d.png) | ![](http://openweathermap.org/img/wn/13n.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664133-69d4d26c-c446-4cd9-99fe-8355cce15520.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664141-c6dd39e3-aee8-4c74-bc77-f9be758d1606.png) |snow
![](http://openweathermap.org/img/wn/50d.png) | ![](http://openweathermap.org/img/wn/50n.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664078-69f8f4bc-b0f4-4cd0-a7c6-aee3fe36d529.png) | ![grafik](https://user-images.githubusercontent.com/87453514/166664089-69743122-7077-42bc-b755-859874c42b61.png) |mist


</body>
</html>

**Comment by lsiebels** [comment]
Since we found a corresponding example for each case at Fontawesome, I would say that if any are also found for naturerobots/digital_logbook#19, we should use Fontawesome.

**Comment by lucaslootalot** [comment]
@dobro929  For the moment, the OpenWeather icons have been integrated.

**Comment by lucaslootalot** [comment]
@dobro929 @fmarahre Is any information still needed here? I would stay with the OWM icons for now. Should these be replaced, I would create a completely new issue.

**Comment by fmarahre** [comment]
@lucaslootalot ok for me

**Comment by fmarahre** [comment]
@lucaslootalot ok for me

**Comment by lucaslootalot** [comment]
I asked Billie if something had to be done about it for now.

**Comment by lsiebels** [comment]
Billie looks for an alternative. 🔍

**Comment by dobro929** [comment]
Update from Billie.
<html><body>


NR icon  | Description
-- | -- 
![01d](https://user-images.githubusercontent.com/87453514/181071299-a896c47b-1eca-4e4d-8b46-ec5ab537e7e3.svg) | clear sky
![02d](https://user-images.githubusercontent.com/87453514/181071322-ea785315-2161-45b5-876c-6672b690f5b6.svg) | few clouds
![03d](https://user-images.githubusercontent.com/87453514/181071335-fb938e89-d4fa-4987-86c7-5eb5fbe34a42.svg) | scattered clouds
coming soon (04d) | broken clouds
![09d](https://user-images.githubusercontent.com/87453514/181072037-ab8f710d-4dda-41ba-91fd-7ec62c6bf539.svg) | shower rain
coming soon (10d) | rain
![11d](https://user-images.githubusercontent.com/87453514/181071373-c2a5209f-75fc-4317-ba0f-3d0eb43a1bbe.svg) | thunderstorm
![13d](https://user-images.githubusercontent.com/87453514/181071392-c3779c69-9da8-42a4-b088-f8e88f92e383.svg) | snow
coming soon (50d) | mist


</body>
</html>
