### ISSUE TITLE
Permission to remove an issue

### ISSUE THREAD

**Issue by lucaslootalot** [naturerobots/HSOS-SEP-PlantMap-2022#27]
Is it possible to give one of the project group the right to delete issues completely?
It would make sense to give this to @jarkenau as the project leader.
If this is not possible or wanted, should we then write another issue to remove the issues?

**Comment by spuetz** [comment]
You cannot remove issues. You can only close issues. I have seen that you have already closed some issues. Please think before you create a new issue. Also, use decent descriptions in the issues. Thank you.

**Comment by spuetz** [comment]
And yes, please write down any issues that should be removed if it is really necessary.

**Comment by lucaslootalot** [comment]
The issues that are to be removed are only issues that arose in the planning phase. There we tried out how we could best organise the requirements. Perhaps I should have mentioned that. We don't want to remove issues that show the progress of the project. In the future, it should no longer happen that unnecessary issues have to be created and removed.

**Comment by lucaslootalot** [comment]
@spuetz Thank you very much!

Since all issues have been removed and the permission to remove them is not up for discussion, I am closing the issue.
