### ISSUE TITLE
dashboard: view

### ISSUE THREAD

**Issue by lucaslootalot** [naturerobots/HSOS-SEP-PlantMap-2022#29]
Based on the following components:

- `sidebar` component

   - [x] #31 
   - [ ] #32 

- `weather` component

   - [x] #28
   - [x] #23  
   - [x] #24  
  
- `gardenmap` component

   - [x] #52
   - [x] #53
   - [x]  #55

- `sensor` component

   - [x]  #56
   - [x]  #57

- `notifications` component

> It must be discussed where the notifications are to be displayed.

**Comment by lsiebels** [comment]
@dobro929 @fmarahre Is there already a plan on how we want to proceed with the notifications or are they obsolete? naturerobots/digital_logbook#20 naturerobots/digital_logbook#11
