### ISSUE TITLE
Integrate a CSS framework and adapt the NR UI Kit v1

### ISSUE THREAD

**Issue by lucaslootalot** [naturerobots/HSOS-SEP-PlantMap-2022#30]
Please integrate a CSS Framework and adapt the NR UI Kit v1.

- [x] integrate a CSS framework
- [x] adapt the NR UI Kit v1 to the CSS framework

Color scheme: [NR_UI_Kit_v1.pdf](https://github.com/naturerobots/HSOS-SEP-PlantMap-2022/files/8590477/NR_UI_Kit_v1.pdf)

**Comment by dobro929** [comment]
Implemented the **basic colors** (theme light) with daisyui and tailwindcss (#15)
