### ISSUE TITLE
Integrate NR Typography

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#43]
- [ ] add `Helvetica` as base font-family
- [ ] if needed, change tailwind **font sizes** [[doc]](https://tailwindcss.com/docs/font-size)
- [ ] adjust the **font weight** to `Light/Regular/Medium` [[doc]](https://tailwindcss.com/docs/font-weight)

**Comment by lucaslootalot** [comment]
On which source is the font based? I could not find any document in which it was clearly defined. We should ask about that. Replacing `Helvetica` with another font should not be the problem.

**Comment by lucaslootalot** [comment]
Any updates here?
