### ISSUE TITLE
gardenmap: integrate Leaflet

### ISSUE THREAD

**Issue by lucaslootalot** [naturerobots/HSOS-SEP-PlantMap-2022#53]
Integrate the Leaflet into the Gardenmap component. For the time being, only an example image is to be displayed.

- [x] integrate Leaflet
- [x] use an example image to display

**Comment by dobro929** [comment]
Implemented first workflow for placing an image on the map with 3 markers. [Leaflet image rotation](https://github.com/IvanSanchez/Leaflet.ImageOverlay.Rotated) was used to perfectly fit the image to the points on the map.

![grafik](https://user-images.githubusercontent.com/87453514/170296360-00906d1b-dae2-4952-b11b-319a7b3f0f7a.png)
