### ISSUE TITLE
gardenmap: display sensors

### ISSUE THREAD

**Issue by lucaslootalot** [naturerobots/HSOS-SEP-PlantMap-2022#55]
Show the position of the sensors on the garden map.

- [x] get data from the sensor store
- [x] display the position on the garden map with a marker

**Comment by jarkenau** [comment]
Planning poker :black_joker: results: 

- Sum: 41
- Average: 5.125

**Comment by dobro929** [comment]
`BaseMap.vue` and `LeafletMap.vue` has been extended that the function **addMarker** can now be used. **Test functions** have already been added in `GardenMap.vue`.
