### ISSUE TITLE
sensor: create

### ISSUE THREAD

**Issue by lucaslootalot** [naturerobots/HSOS-SEP-PlantMap-2022#56]
Create the basic sensor component to display sensor data.

- [x] create `SensorComp.vue` component

**Comment by dobro929** [comment]
**Up/Down-Arrows** for the sensor trend ![arrow_down](https://user-images.githubusercontent.com/87453514/167824682-ed23807d-1304-4676-ade8-c929547789c2.svg)![arrow_up](https://user-images.githubusercontent.com/87453514/167824162-5add1587-fa58-44fc-b445-5bcc77a32a51.svg)

**Comment by lucaslootalot** [comment]
User story example:
![image](https://user-images.githubusercontent.com/57572111/167840676-6200b7b9-5079-4616-8ae6-fe2dba43ea10.png)

**Comment by lucaslootalot** [comment]
The basic component `SensorComp.vue` has been created and consists of individual `SensorStatus.vue` components. These still receive the data statically as a prop. This is then taken over by a store. 

![image](https://user-images.githubusercontent.com/57572111/167952153-b1b372a5-ba5c-4cdf-a6d6-daa03a195c21.png)

**Comment by lucaslootalot** [comment]
Closed with merged PR.
