### ISSUE TITLE
dashboard: layout

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#60]
Create the basic layout with [Flexbox & Grid](https://tailwindcss.com/docs/flex-basis).

grid | col 1 | col 2 | col 3 
-- | -- | -- | --
row 1 | weather | gardenmap | gardenmap 
row 2 | sensor   | gardenmap | gardenmap

**Comment by lucaslootalot** [comment]
Closed with merged PR.
