### ISSUE TITLE
Save Data in Django Backend

### ISSUE THREAD

**Issue by lniehaus** [naturerobots/HSOS-SEP-PlantMap-2022#70]
The PLY Files need to be stored somewhere. The Frontend needs to be able to access these Files.

**Comment by jarkenau** [comment]
Planning poker :black_joker: results: 

- Sum: 173
- Average: 21.625

**Comment by lniehaus** [comment]
The files get saved in the storage. Next the files need to be accessible in the Frontend. This will be continued in this Issue: https://github.com/naturerobots/HSOS-SEP-PlantMap-2022/issues/118
