### ISSUE TITLE
asynchronous jobs for querying data from SEEREP

### ISSUE THREAD

**Issue by jarkenau** [naturerobots/HSOS-SEP-PlantMap-2022#71]
Look into ways for using asynchronous jobs in django for quarrying data from SEEREP. An example job, could be saving the received point clouds onto the local hard drive.

**Comment by lniehaus** [comment]
Buzzwords: DjangoQ, Celery

**Comment by jarkenau** [comment]
Planning poker :black_joker: results: 

- Sum: 92
- Average: 11.5
