### ISSUE TITLE
implement quasar framework

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#80]
- [x] redesign components
     - [x] WeatherComp (old version)
     - [x] SidebarMenu
     - [x] LoginForm
     - [x] SensorComp
     - [x] ImageCrop
     - [x] BaseMap
     - [x] Cropstable
 - [x] when all comps have been redesigned, `remove daisyui`

**Comment by jarkenau** [comment]
Planning poker :black_joker: results: 

- Sum: 73
- Average: 9.125
