### ISSUE TITLE
interaction between cropstable and cropsmap

### ISSUE THREAD

**Issue by dobro929** [naturerobots/HSOS-SEP-PlantMap-2022#85]
- [x] draw demo polygons for all demo crops
- [x] implement hover interaction table-->map 
- [x] implement hover interaction table<--map

**Comment by jarkenau** [comment]
Planning poker :black_joker: results: 

- Sum: 77
- Average: 9.625

**Comment by dobro929** [comment]
`BaseMap.vue` and `LeafletMap.vue` has been extended that the function **addPolygon** can now be used. **Test functions** have already been added in `CropsMap.vue`.

**Comment by lucaslootalot** [comment]
@fmarahre Can the issue be closed?
