### ISSUE TITLE
Create Image Tiles for Leaflet

### ISSUE THREAD

**Issue by lniehaus** [naturerobots/HSOS-SEP-PlantMap-2022#92]
Open Streetmap Tile Provider

**Comment by lniehaus** [comment]
vue/src/components/Leaflet/LeafletComp.vue
enthält Beispieldaten.
Leaflet Doku: TileLayer

**Comment by lniehaus** [comment]
https://nithanaroy.medium.com/create-your-own-tile-server-and-map-client-5f7515fff28

**Comment by lniehaus** [comment]
Instead of loading one big image leaflet can load a tiled images, so it only gets the sub images it needs. These tiles need to be generated.

**Comment by jarkenau** [comment]
Probably more useful: https://gis.stackexchange.com/questions/285483/how-can-i-convert-an-image-into-map-tiles-for-leafletjs

**Comment by jarkenau** [comment]
To-dos:

- [ ] Georeference image from received coordinates
- [ ] Generate tiles from image, probably with https://gdal.org/programs/gdal2tiles.html
- [ ] Create API Endpoints for getting the tiles, the path should follow: https://leafletjs.com/reference.html#tilelayer

**Comment by jarkenau** [comment]
Closing this, due to because we don't see a huge advantage in a tile server, since the images of the beds are currently pretty small, and we only got one available.
