### ISSUE TITLE
Define explicit names

### ISSUE THREAD

**Issue by lucaslootalot** [naturerobots/HSOS-SEP-PlantMap-2022#99]
Also with regard to the documentation, I wanted us to record the explicit identifiers for once. I myself still get confused about what is meant by what. 

A: Bed / Row ?
B: Garden / Bed ?
C (Everything around) : Companie  / Garden ? 

If there are other terms that need to be defined now, I would say that will also be clarified here.

![org_53a73328457a1572_1567260440000 (1)](https://user-images.githubusercontent.com/57572111/172909947-0d19b878-4d2f-437b-b74f-84f1ff714bdf.jpg)

**Comment by jarkenau** [comment]
Good idea, I created an Issue for the documentation #101, where we should write down the term definitions.

**Comment by lucaslootalot** [comment]
@jarkenau  For unclear definitions, I would still open a separate issue and also discuss the current definitions in this issue here.

**Comment by lucaslootalot** [comment]
@gwoeckner Do you have a clear definition for us? 😄

**Comment by lucaslootalot** [comment]
@jarkenau Do we then wait until #101  is completed to add the definitions?

**Comment by jarkenau** [comment]
You can contribute to the documentation when ever you want.

**Comment by lucaslootalot** [comment]
Documentation updated. 👍🏻
